wandb_version: 1

max_epochs:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 1.0e-05
image_size:
  desc: null
  value: 1024
train_steps:
  desc: null
  value: 100
val_steps:
  desc: null
  value: 2500
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691447360.651246
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.8
      6: 4.31.0
      8:
      - 5
