# Generated by Django 3.2.16 on 2023-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('document_type', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
