# Generated by Django 3.2.16 on 2023-03-17 22:57

from django.db import migrations


def create_data(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    Document.objects.create(name='test', document_type='test', image=bytes())


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
    ]
