# Generated by Django 4.1.7 on 2023-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="image",
            field=models.BinaryField(),
        ),
    ]
